// <auto-generated />
namespace CrudWebApiAngularJs.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ToSqlExpress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ToSqlExpress));
        
        string IMigrationMetadata.Id
        {
            get { return "201605211109079_ToSqlExpress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
